services:
  neo4j:
    image: neo4j:5.11-community
    container_name: repochat-neo4j-test
    ports:
      - "7474:7474"   # Browser interface
      - "7687:7687"   # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/repochat123
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server_config_strict__validation_enabled=false
    volumes:
      - neo4j_test_data:/data
      - neo4j_test_logs:/logs
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "repochat123", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - repochat-test

  repochat-backend:
    build: 
      context: .
      dockerfile: Dockerfile.test
    container_name: repochat-backend-test
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=repochat123
      - PYTHONPATH=/app/src
      - LOG_LEVEL=INFO
    volumes:
      - .:/app
      - /tmp/repochat-test:/tmp/repochat-test
      - repochat_test_cache:/app/.cache
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - repochat-test

volumes:
  neo4j_test_data:
    driver: local
  neo4j_test_logs:
    driver: local
  repochat_test_cache:
    driver: local

networks:
  repochat-test:
    driver: bridge 